### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by dreynolds** [danielkaczmarczyk/guitar_practice_generator#12]
Might it be worth adding some tests at this early stage before we get too far along?

**Comment by danielkaczmarczyk** [comment]
Yeah, I was thinking about testing. Shoot with any ideas!

**Comment by dreynolds** [comment]
How do you feel about using something like https://travis-ci.org ?

**Comment by danielkaczmarczyk** [comment]
I'll take a look into it!
